apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: devops-demo
  template:
    metadata:
      labels:
        app: devops-demo
    spec:
      containers:
      - name: devops-container
        image: jeevan073/devops-demo:22      # must match your pushed tag
        imagePullPolicy: Always              # ensures Kubernetes always pulls latest
      imagePullSecrets:                      # if your repo is private (Docker Hub public doesn't need this)
      - name: your-docker-secret
